using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Jeedom.Model
{
    public enum GenericTypeEnum
    {
        
        LIGHT_STATE,
        LIGHT_ON,
        LIGHT_OFF,
        LIGHT_SLIDER,
        LIGHT_COLOR,
        LIGHT_SET_COLOR,
        ENERGY_STATE,
        ENERGY_ON,
        ENERGY_OFF,
        ENERGY_SLIDER,
        FLAP_STATE,
        FLAP_UP,
        FLAP_DOWN,
        FLAP_STOP,
        FLAP_SLIDER,
        FLAP_BSO_STATE,
        FLAP_BSO_UP,
        FLAP_BSO_DOWN,
        HEATING_ON,
        HEATING_OFF,
        HEATING_STATE,
        HEATING_OTHER,
        LOCK_STATE,
        LOCK_OPEN,
        LOCK_CLOSE,
        SIREN_STATE,
        SIREN_OFF,
        SIREN_ON,
        THERMOSTAT_STATE,
        THERMOSTAT_TEMPERATURE,
        THERMOSTAT_SET_SETPOINT,
        THERMOSTAT_SETPOINT,
        THERMOSTAT_SET_MODE,
        THERMOSTAT_MODE,
        THERMOSTAT_SET_LOCK,
        THERMOSTAT_LOCK,
        MODE_STATE,
        MODE_SET_STATE,
        ALARM_STATE,
        ALARM_MODE,
        ALARM_ENABLE_STATE,
        ALARM_ARMED,
        ALARM_RELEASED,
        ALARM_SET_MODE,
        POWER,
        CONSUMPTION,
        TEMPERATURE,
        BRIGHTNESS,
        PRESENCE,
        BATTERY,
        SMOKE,
        FLOOD,
        HUMIDITY,
        UV,
        OPENING,
        SABOTAGE,
        CO2,
        VOLTAGE,
        NOISE,
        PRESSURE,
        RAIN_CURRENT,
        RAIN_TOTAL,
        WIND_SPEED,
        WIND_DIRECTION,
        GENERIC,
        DONT,
    }
}